import { uuid } from "@/utils/cmmon";

export const configrationTableData = [
    {
        id: uuid(),
        countryCode: "+92",
        countryName: "Pakistan",
        currency: "PKR",
        creationDate: "12/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+91",
        countryName: "India",
        currency: "INR",
        creationDate: "13/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+93",
        countryName: "Afghanistan",
        currency: "AFN",
        creationDate: "12/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+94",
        countryName: "Sri Lanka",
        currency: "LKR",
        creationDate: "13/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+977",
        countryName: "Nepal",
        currency: "NPR",
        creationDate: "13/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+960",
        countryName: "Maldives",
        currency: "MVR",
        creationDate: "13/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+971",
        countryName: "United Arab Emirates",
        currency: "AED",
        creationDate: "13/10/2024",
        status: "Inactive",
    },
    {
        id: uuid(),
        countryCode: "+966",
        countryName: "Saudi Arabia",
        currency: "SAR",
        creationDate: "13/10/2024",
        status: "Inactive",
    },
    {
        id: uuid(),
        countryCode: "+65",
        countryName: "Singapore",
        currency: "SGD",
        creationDate: "13/10/2024",
        status: "Active",
    },
    {
        id: uuid(),
        countryCode: "+1",
        countryName: "United States of America",
        currency: "USD",
        creationDate: "13/10/2024",
        status: "Inactive",
    },
];