export const foodPermitDeductionTableData = [
    {
        id: "AB0001",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-f-f.png",
        email: "saleem@gmail.com",
        resident: "UAE",
        bikeRegistrationCity: "Dubai",
        workingCity: "Ajman",
        bikeNo: "ABC-05123",
        drivingLicense: "879343",
        foodPermitNumber: "123456789",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0002",
        fullName: "MD Kulem Ullah MD Sukwor",
        email: "saleem@gmail.com",
        image: "/images/profile-f-f.png",
        resident: "UAE",
        bikeRegistrationCity: "Dubai",
        workingCity: "Ajman",
        bikeNo: "ABC-05123",
        drivingLicense: "879343",
        foodPermitNumber: "123456789",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0003",
        fullName: "MD Kulem Ullah MD Sukwor",
        email: "saleem@gmail.com",
        image: "/images/profile-f-f.png",
        resident: "UAE",
        bikeRegistrationCity: "Dubai",
        workingCity: "Ajman",
        bikeNo: "ABC-05123",
        drivingLicense: "879343",
        foodPermitNumber: "123456789",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0004",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        email: "saleem@gmail.com",
        image: "/images/profile-m-m.png",
        resident: "UAE",
        bikeRegistrationCity: "Dubai",
        workingCity: "Ajman",
        bikeNo: "ABC-05123",
        drivingLicense: "879343",
        foodPermitNumber: "123456789",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },
    {
        id: "AB0005",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        email: "saleem@gmail.com",
        image: "/images/profile-f.jpg",
        resident: "UAE",
        bikeRegistrationCity: "Dubai",
        workingCity: "Ajman",
        bikeNo: "ABC-05123",
        drivingLicense: "879343",
        foodPermitNumber: "123456789",
        passportNumber: "TA1822801",
        phoneNumber: "+971 986556465",
        employeeType: "Rider",
    },

];


export const mainTableData = [
    {
        id: "AB0001",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-f.jpg",
        date: "13/03/2024",
        amountChargedToRider: "1500",
        deductionType: "Variable",
        installmentPlans: "3 Months",
        approvalDate: "--",
        status: "Pending",

    },
    {
        id: "AB0002",
        fullName: "Saleem Akhtar Muhammad Miskeen",
        image: "/images/profile-f.jpg",
        date: "13/03/2024",
        amountChargedToRider: "1500",
        deductionType: "Variable",
        installmentPlans: "3 Months",
        approvalDate: "--",
        status: "Pending",

    },
]

