export const loanMainTableData = [
    {
      "id": "AB00001",
      "fullName": "Saleem Akhtar Muhammad Miskeen",
      "email": "saleemakhtar@gmail.com",
      "date": "12/20/24",
      "reasonForLoan": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Fixed",
      "status": "In Progress"
    },
    {
      "id": "AB00002",
      "fullName": "MD Kulem Ullah MD Sukwor",
      "email": "mdkulem@gmail.com",
      "date": "12/20/24",
      "loanForReason": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Variable",
      "status": "Completed"
    },
    {
      "id": "AB00002",
      "fullName": "MD Kulem Ullah MD Sukwor",
      "email": "mdkulem@gmail.com",
      "date": "12/20/24",
      "loanForReason": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Variable",
      "status": "Completed"
    },
    {
      "id": "AB00002",
      "fullName": "MD Kulem Ullah MD Sukwor",
      "email": "mdkulem@gmail.com",
      "date": "12/20/24",
      "loanForReason": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Variable",
      "status": "Completed"
    },
    {
      "id": "AB00002",
      "fullName": "MD Kulem Ullah MD Sukwor",
      "email": "mdkulem@gmail.com",
      "date": "12/20/24",
      "loanForReason": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Variable",
      "status": "Completed"
    },
    {
      "id": "AB00002",
      "fullName": "MD Kulem Ullah MD Sukwor",
      "email": "mdkulem@gmail.com",
      "date": "12/20/24",
      "loanForReason": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Variable",
      "status": "Completed"
    },
    {
      "id": "AB00002",
      "fullName": "MD Kulem Ullah MD Sukwor",
      "email": "mdkulem@gmail.com",
      "date": "12/20/24",
      "loanForReason": "Any...",
      "visaStatus": "ABDS",
      "purchaseCost": 6000,
      "visaLoanAmountChargedToRider": 7000,
      "advanceReceived": 7000,
      "deductionType": "Variable",
      "status": "Completed"
    },
  
  ]
  