// export const columns = [
//     { field: "date", headerName: "DATE", align: "left" },
//     { field: "fullName", headerName: "FULL NAME", align: "left" },
//     { field: "residentCountry", headerName: "RESIDENT COUNTRY", align: "left" },
//     { field: "residentCity", headerName: "RESIDENT CITY", align: "left" },
//     { field: "drivingLicense", headerName: "DRIVING LICENSE", align: "left" },
//     { field: "phoneNumber", headerName: "PHONE NUMBER", align: "left" },
//     { field: "campaignName", headerName: "CAMPAIGN NAME", align: "left" },
//     { field: "remarks", headerName: "REMARKS", align: "left" },
//     {
//         field: "status",
//         headerName: "STATUS",
//         align: "left",showFilter:true,
//         render: (row) => (
//             <Box
//                 sx={{
//                     backgroundColor: row.status === "Pending" ? "#D9F0FF" : "#FFE5E5",
//                     color: row.status === "Pending" ? "#007FFF" : "#FF0000",
//                     padding: "4px 8px",
//                     borderRadius: "4px",
//                 }}
//             >
//                 {row.status}
//             </Box>
//         ),
//     },
// ];

export const data = [
  {
    key: "1",
    date: "12/09/2024",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-f.jpg",
    residentCountry: "Pakistan",
    residentCity: "Karachi",
    drivingLicense: "Yes",
    phoneNumber: "+92 316 556 4650",
    campaignName: "Winter Fair",
    remarks: "--",
    status: "Pending",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Incomplete Profile",
    status2: "Active",
    id: "AB00001",
    status3: "InActive",
  },
  {
    key: "2",
    date: "13/09/2024",
    fullName: "Kulem Ullah",
    email: "kulem@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "India",
    residentCity: "Mumbai",
    drivingLicense: "No",
    phoneNumber: "+91 456 576 5460",
    campaignName: "Tech Expo",
    remarks: "Will be available after 2 days",
    status: "On Hold",
    action: "Edit",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB000012",
    status3: "InActive",
  },
  {
    key: "3",
    date: "14/09/2024",
    fullName: "Aisha Khan",
    email: "aisha@gmail.com",
    image: "https://example.com/images/profile-aisha.jpg",
    residentCountry: "Pakistan",
    residentCity: "Islamabad",
    drivingLicense: "Yes",
    phoneNumber: "+92 300 123 4567",
    campaignName: "Marketing Summit",
    remarks: "Experienced Marketer",
    status: "Pending",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB000013",
    status3: "InActive",
  },
  {
    key: "4",
    date: "15/09/2024",
    fullName: "John Smith",
    email: "john@gmail.com",
    image: "https://example.com/images/profile-john.jpg",
    residentCountry: "USA",
    residentCity: "New York",
    drivingLicense: "Yes",
    phoneNumber: "+1 234 567 8900",
    campaignName: "Blockchain Meetup",
    remarks: "--",
    status: "Confirmed",
    action: "Edit",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Incomplete Profile",
    status2: "Active",
    id: "AB000014",
    status3: "InActive",
  },
  {
    key: "5",
    date: "16/09/2024",
    fullName: "Emily Rose",
    email: "emily@gmail.com",
    image: "https://example.com/images/profile-emily.jpg",
    residentCountry: "Canada",
    residentCity: "Toronto",
    drivingLicense: "No",
    phoneNumber: "+1 647 123 4567",
    campaignName: "AI Workshop",
    remarks: "Needs accommodation",
    status: "Pending",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Incomplete Profile",
    status2: "Active",
    id: "AB000015",
    status3: "InActive",
  },
  {
    key: "6",
    date: "17/09/2024",
    fullName: "Ali Hassan",
    email: "ali@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "Pakistan",
    residentCity: "Lahore",
    drivingLicense: "Yes",
    phoneNumber: "+92 321 555 4321",
    campaignName: "Startup Pitch Fest",
    remarks: "--",
    status: "On Hold",
    action: "Edit",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB000016",
    status3: "InActive",
  },

  {
    key: "15",
    date: "26/09/2024",
    fullName: "Liam Jackson",
    email: "liam@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "Canada",
    residentCity: "Vancouver",
    drivingLicense: "No",
    phoneNumber: "+1 604 123 9876",
    campaignName: "AI Workshop",
    remarks: "--",
    status: "Pending",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB0000115",
    status3: "InActive",
  },
  {
    key: "16",
    date: "27/09/2024",
    fullName: "Mia Taylor",
    email: "mia@gmail.com",
    image: "https://example.com/images/profile-mia.jpg",
    residentCountry: "Australia",
    residentCity: "Melbourne",
    drivingLicense: "Yes",
    phoneNumber: "+61 450 123 987",
    campaignName: "Startup Pitch Fest",
    remarks: "Investor",
    status: "Confirmed",
    action: "Edit",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB0000116",
    status3: "InActive",
  },
  {
    key: "17",
    date: "28/09/2024",
    fullName: "Ali Raza",
    email: "ali.raza@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "Pakistan",
    residentCity: "Faisalabad",
    drivingLicense: "Yes",
    phoneNumber: "+92 345 789 6541",
    campaignName: "Healthcare Expo",
    remarks: "--",
    status: "Pending",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB0000117",
    status3: "InActive",
  },
  {
    key: "18",
    date: "29/09/2024",
    fullName: "Sara Parker",
    email: "sara@gmail.com",
    image: "https://example.com/images/profile-sara.jpg",
    residentCountry: "USA",
    residentCity: "Boston",
    drivingLicense: "No",
    phoneNumber: "+1 617 555 1234",
    campaignName: "Education Forum",
    remarks: "--",
    status: "Confirmed",
    action: "Edit",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB0000118",
    status3: "InActive",
  },
  {
    key: "19",
    date: "30/09/2024",
    fullName: "Omar Farooq",
    email: "omar@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "Pakistan",
    residentCity: "Multan",
    drivingLicense: "Yes",
    phoneNumber: "+92 333 654 9870",
    campaignName: "Green Energy Summit",
    remarks: "--",
    status: "Pending",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB0000119",
    status3: "InActive",
  },
  {
    key: "20",
    date: "01/10/2024",
    fullName: "Isabella Wilson",
    email: "isabella@gmail.com",
    image: "https://example.com/images/profile-isabella.jpg",
    residentCountry: "Canada",
    residentCity: "Calgary",
    drivingLicense: "No",
    phoneNumber: "+1 403 555 7890",
    campaignName: "E-Commerce Innovations Expo",
    remarks: "--",
    status: "Confirmed",
    action: "View Details",
    drivingLicenseNo: "35444218797863",
    passportNo: "TA1822801",
    preferedWorkingCity: "Dubai",
    referBy: "John Smith",
    status1: "Hold",
    status2: "Active",
    id: "AB0000120",
    id: "AB00001",
    status3: "InActive",
  },
];

export const eventData = [
  {
    id: 1,
    eventName: "Tech Conference 2024",
    totalApplied: 120,
    creationDate: "2023-11-01",
    description: "Explore cutting-edge innovations in technology.",
    startDate: "2024-01-15",
    endDate: "2024-01-18",
    link: "https://example.com/tech-conference",
    active: true,
    bgColor: ["#4A90E2", "#50E3C2"], // Cool tech-inspired gradient
  },
  {
    id: 2,
    eventName: "AI & Machine Learning Summit",
    totalApplied: 95,
    creationDate: "2023-09-20",
    description: "Discover the latest advancements in AI and ML.",
    startDate: "2024-02-10",
    endDate: "2024-02-12",
    link: "https://example.com/ai-ml-summit",
    active: true,
    bgColor: ["#8E44AD", "#3498DB"], // Futuristic AI vibe
  },
  {
    id: 3,
    eventName: "Startup Pitch Fest",
    totalApplied: 50,
    creationDate: "2023-10-10",
    description: "Platform for startups to showcase their innovations.",
    startDate: "2024-03-01",
    endDate: "2024-03-03",
    link: "https://example.com/pitch-fest",
    active: false,
    bgColor: ["#16A085", "#2ECC71"], // Fresh entrepreneurial energy
  },
  {
    id: 4,
    eventName: "Marketing Summit",
    totalApplied: 200,
    creationDate: "2023-08-25",
    description: "Deep dive into the latest marketing strategies.",
    startDate: "2024-04-10",
    endDate: "2024-04-12",
    link: "https://example.com/marketing-summit",
    active: true,
    bgColor: ["#E74C3C", "#F1C40F"], // Bold, vibrant marketing colors
  },
  {
    id: 5,
    eventName: "Healthcare Innovations Expo",
    totalApplied: 310,
    creationDate: "2023-06-30",
    description: "Showcase of cutting-edge advancements in healthcare.",
    startDate: "2024-05-20",
    endDate: "2024-05-22",
    link: "https://example.com/healthcare-expo",
    active: true,
    bgColor: ["#27AE60", "#2980B9"], // Calming healthcare tones
  },
  {
    id: 6,
    eventName: "Blockchain Developers Meetup",
    totalApplied: 75,
    creationDate: "2023-10-15",
    description: "A networking event for blockchain enthusiasts.",
    startDate: "2024-06-05",
    endDate: "2024-06-06",
    link: "https://example.com/blockchain-meetup",
    active: false,
    bgColor: ["#2C3E50", "#8E44AD"], // Futuristic blockchain gradient
  },
  {
    id: 7,
    eventName: "Creative Design Conference",
    totalApplied: 150,
    creationDate: "2023-07-12",
    description: "Explore trends and techniques in modern design.",
    startDate: "2024-07-10",
    endDate: "2024-07-12",
    link: "https://example.com/design-conference",
    active: true,
    bgColor: ["#F39C12", "#E67E22"], // Creative, artistic tones
  },
  {
    id: 8,
    eventName: "Education Leaders Forum",
    totalApplied: 90,
    creationDate: "2023-09-05",
    description: "Discuss innovations shaping the future of education.",
    startDate: "2024-08-01",
    endDate: "2024-08-03",
    link: "https://example.com/education-forum",
    active: true,
    bgColor: ["#3498DB", "#1ABC9C"], // Bright, optimistic education colors
  },
  {
    id: 9,
    eventName: "Cybersecurity Challenges Summit",
    totalApplied: 110,
    creationDate: "2023-11-10",
    description: "Addressing modern cybersecurity challenges.",
    startDate: "2024-09-15",
    endDate: "2024-09-17",
    link: "https://example.com/cybersecurity-summit",
    active: false,
    bgColor: ["#34495E", "#2C3E50"], // Dark and secure tones
  },
  {
    id: 10,
    eventName: "E-Commerce Innovations Expo",
    totalApplied: 220,
    creationDate: "2023-05-20",
    description: "Explore innovations driving modern e-commerce.",
    startDate: "2024-10-05",
    endDate: "2024-10-07",
    link: "https://example.com/ecommerce-expo",
    active: true,
    bgColor: ["#1ABC9C", "#16A085"], // Fresh and vibrant retail colors
  },
  {
    id: 11,
    eventName: "Sustainable Energy Summit",
    totalApplied: 140,
    creationDate: "2023-06-10",
    description: "Highlighting sustainable energy solutions.",
    startDate: "2024-11-20",
    endDate: "2024-11-22",
    link: "https://example.com/green-energy",
    active: true,
    bgColor: ["#27AE60", "#2ECC71"], // Earthy green tones
  },
  {
    id: 12,
    eventName: "Space Exploration Forum",
    totalApplied: 180,
    creationDate: "2023-07-30",
    description: "Advancements in space technology and exploration.",
    startDate: "2024-12-01",
    endDate: "2024-12-03",
    link: "https://example.com/space-tech",
    active: true,
    bgColor: ["#8E44AD", "#2C3E50"], // Cosmic and futuristic tones
  },
];

export const companyTableData = [
  {
    key: "1",
    date: "12/09/2024",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-f.jpg",
    residentCountry: "Pakistan",
    residentCity: "Karachi",
    phoneNumber: "+92 316 556 4650",
    role: "Admin",
  },
  {
    key: "2",
    date: "12/09/2024",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-f.jpg",
    residentCountry: "Pakistan",
    residentCity: "Karachi",
    phoneNumber: "+92 316 556 4650",
    role: "Admin",
  },
  {
    key: "3",
    date: "12/09/2024",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "Pakistan",
    residentCity: "Karachi",
    phoneNumber: "+92 316 556 4650",
    role: "Admin",
  },
  {
    key: "4",
    date: "12/09/2024",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-f.jpg",
    residentCountry: "Pakistan",
    residentCity: "Karachi",
    phoneNumber: "+92 316 556 4650",
    role: "Admin",
  },
  {
    key: "5",
    date: "12/09/2024",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-m.jpg",
    residentCountry: "Pakistan",
    residentCity: "Karachi",
    phoneNumber: "+92 316 556 4650",
    role: "Admin",
  },
];
