// export const challanData = [
//     {
//       invoiceMonth: "Aug, 2024",
//       vendorName: "Easy Lease",
//       dateOfSalik: "07-08-2024",
//       transactionId: "378674906",
//       registrationNo: "14768",
//       salikAmount: { amount: 1500, currency: "AED" },
//       tollGate: "Al Mamzar North",
//       direction: "Abu Dhabi",
//       id: "AB00009",
//       bikePlateNo: "43234",
//       challanAmount: { amount: 1500, currency: "AED" },
//       challanNumber: "097643213221",
//       city: "Sharjah",
//       location: "Salahuddin Rd Deira, Sharjah",
//       reason: "Traffic Signal",
//       dateTimeTrafficChallan: "12/08/2024 12:00 PM",
//       challanAttachments: {
//         id: '3',
//         name: "Driver's License Scan",
//         type: 'image',
//         size: '800 KB',
//         uploadDate: '2023-12-02'
//       },    
//       remarks: "He is breaking signals again and again",
//       bikeOwner: "ABDS",
//       createdOn: "12/09/2024",
//       status: "Unpaid",
//       action: "..."
//     },
//     {
//       invoiceMonth: "Aug, 2024",
//       vendorName: "Easy Lease",
//       dateOfSalik: "07-08-2024",
//       transactionId: "378674907",
//       registrationNo: "14769",
//       salikAmount: { amount: 1200, currency: "AED" },
//       tollGate: "Al Mamzar South",
//       direction: "Sharjah",
//       id: "AB00010",
//       bikePlateNo: "43235",
//       challanAmount: { amount: 1500, currency: "AED" },
//       challanNumber: "097643213222",
//       city: "Dubai",
//       location: "Salahuddin Rd Deira, Dubai",
//       reason: "Traffic Signal",
//       dateTimeTrafficChallan: "12/08/2024 12:00 PM",
//       challanAttachments: {
//         id: '4',
//         name: "Driver's License Scan",
//         type: 'image',
//         size: '800 KB',
//         uploadDate: '2023-12-02'
//       },    
//       remarks: "---",
//       bikeOwner: "ABDS",
//       createdOn: "12/09/2024",
//       status: "Paid",
//       action: "..."
//     },
//     {
//       invoiceMonth: "Jul, 2024",
//       vendorName: "Smart Rentals",
//       dateOfSalik: "30-07-2024",
//       transactionId: "378674909",
//       registrationNo: "14771",
//       salikAmount: { amount: 800, currency: "AED" },
//       tollGate: "Al Barsha",
//       direction: "Abu Dhabi",
//       id: "AB00011",
//       bikePlateNo: "43236",
//       challanAmount: { amount: 800, currency: "AED" },
//       challanNumber: "097643213223",
//       city: "Abu Dhabi",
//       location: "Corniche Rd",
//       reason: "Overspeeding",
//       dateTimeTrafficChallan: "11/07/2024 11:00 AM",
//       challanAttachments: {
//         id: '5',
//         name: "Driver's License Scan",
//         type: 'image',
//         size: '800 KB',
//         uploadDate: '2023-12-02'
//       },
//       remarks: "Driver exceeded speed limit",
//       bikeOwner: "XYZ Rentals",
//       createdOn: "12/09/2024",
//       status: "Unpaid",
//       action: "..."
//     }
//     // Add more dummy entries as needed
//   ];
  


export const challanData = [
    {
      invoiceMonth: "Aug, 2024",
      vendorName: "Easy Lease",
      dateOfSalik: "07-08-2024",
      transactionId: "378674906",
      registrationNo: "14768",
      salikAmount: { amount: 1500, currency: "AED" },
      tollGate: "Al Mamzar North",
      direction: "Abu Dhabi",
      id: "AB00009",
      bikePlateNo: "43234",
      challanAmount: { amount: 1500, currency: "AED" },
      challanNumber: "097643213221",
      city: "Sharjah",
      location: "Salahuddin Rd Deira, Sharjah",
      reason: "Traffic Signal",
      dateTimeTrafficChallan: "12/08/2024 12:00 PM",
      challanAttachments: {
        id: '3',
        name: "Driver's License Scan",
        type: 'image',
        size: '800 KB',
        uploadDate: '2023-12-02'
      },    
      remarks: "He is breaking signals again and again",
      bikeOwner: "ABDS",
      createdOn: "12/09/2024",
      status: "Unpaid",
      action: "..."
    },
    {
      invoiceMonth: "Aug, 2024",
      vendorName: "Easy Lease",
      dateOfSalik: "07-08-2024",
      transactionId: "378674907",
      registrationNo: "14769",
      salikAmount: { amount: 1200, currency: "AED" },
      tollGate: "Al Mamzar South",
      direction: "Sharjah",
      id: "AB00010",
      bikePlateNo: "43235",
      challanAmount: { amount: 1500, currency: "AED" },
      challanNumber: "097643213222",
      city: "Dubai",
      location: "Salahuddin Rd Deira, Dubai",
      reason: "Traffic Signal",
      dateTimeTrafficChallan: "12/08/2024 12:00 PM",
      challanAttachments: {
        id: '4',
        name: "Driver's License Scan",
        type: 'image',
        size: '800 KB',
        uploadDate: '2023-12-02'
      },    
      remarks: "---",
      bikeOwner: "ABDS",
      createdOn: "12/09/2024",
      status: "Paid",
      action: "..."
    },
    {
      invoiceMonth: "Jul, 2024",
      vendorName: "Smart Rentals",
      dateOfSalik: "30-07-2024",
      transactionId: "378674909",
      registrationNo: "14771",
      salikAmount: { amount: 800, currency: "AED" },
      tollGate: "Al Barsha",
      direction: "Abu Dhabi",
      id: "AB00011",
      bikePlateNo: "43236",
      challanAmount: { amount: 800, currency: "AED" },
      challanNumber: "097643213223",
      city: "Abu Dhabi",
      location: "Corniche Rd",
      reason: "Overspeeding",
      dateTimeTrafficChallan: "11/07/2024 11:00 AM",
      challanAttachments: {
        id: '5',
        name: "Driver's License Scan",
        type: 'image',
        size: '800 KB',
        uploadDate: '2023-12-02'
      },
      remarks: "Driver exceeded speed limit",
      bikeOwner: "XYZ Rentals",
      createdOn: "12/09/2024",
      status: "Unpaid",
      action: "..."
    }
  ];
  
  