import { Edit } from "lucide-react";
import { EditIcon } from "./Icons";

export const payrollTableData = [
  {
    id: "AB00001",
    name: "Saleem Ashfaq Muhammad Shehzad",
    image: "/images/profile-f-f.png",
    platformId: "589645",
    visaStatus: "Own",
    joiningDate: "02-01-2024",
    workDays: "29",
    perfectAttendance: "-",
    totalDeliveries: "300",
    totalEarning: "500",
    specialAllowance: "-",
    vendorShare: "400",
    salik: "-",
    trafficChallan: "150",
    foodPermit: "50",
    loanDeduction: {
      amount1: "1300",
      amount2: "500",
    },
    salaryAdvance: "2700",
    cod: "2700",
    generalDeduction: "-",
    penalty: "-",
    totalDeduction: "-",
    nerSalary: "-",
    previousAdjustment: "-",
    netSalaryTransfer: "-",
  },
  {
    id: "AB00002",
    name: "MD Kulem Ullah MD Sukwor",
    image: "/images/profile-f-f.png",
    platformId: "589646",
    visaStatus: "ABDS",
    joiningDate: "02-01-2024",
    workDays: "29",
    perfectAttendance: "-",
    totalDeliveries: "300",
    totalEarning: "500",
    specialAllowance: "-",
    vendorShare: "400",
    salik: "-",
    trafficChallan: "150",
    foodPermit: "50",
    loanDeduction: {
      amount1: "1300",
      amount2: "500",
    },
    salaryAdvance: "2700",
    cod: "2700",
    generalDeduction: "-",
    penalty: "-",
    totalDeduction: "-",
    nerSalary: "-",
    previousAdjustment: "-",
    netSalaryTransfer: "-",
  },
];

export const payrollTableData1 = [
  {
    id: "589645",
    name: "Saleem Ashfaq Muhammad Shehzad",
    image: "/images/profile-f-f.png",
    acquiringCompany: "Noon",
    providingCompany: "ABDS",
    grossSalary: "4000",
    totalDeduction: {
      amount1: "1300",
      amount2: "500",
    },
    totoalSalaryPaid: "3500",
    riderPlatformStatus: "Single Platform",
    processSalary: "3500",
    holdTemporarily: "-",
    holdPermanently: "-",
    comments: "-",
  },
  {
    id: "589645",
    name: "Saleem Ashfaq Muhammad Shehzad",
    image: "/images/profile-f-f.png",
    acquiringCompany: "Noon",
    providingCompany: "ABDS",
    grossSalary: "4000",
    totalDeduction: {
      amount1: "1300",
      amount2: "500",
    },
    totoalSalaryPaid: "3500",
    riderPlatformStatus: "Single Platform",
    processSalary: "3500",
    holdTemporarily: "-",
    holdPermanently: "-",
    comments: "-",
  },
];
