export const permissions = [
    {
      name: "Companies",
      level: 0,
      permissions: ["view", "add", "edit", "delete"],
      customPermissions: ["Add Companies"],
    },
    {
      name: "Campaigns",
      level: 0,
      permissions: ["view"],
      customPermissions: [],
    },
    {
      name: "Campaign List",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Campaign", "Edit Campaign", "Delete Campaign", "Status", "Copy Link"],
    },
    {
      name: "Not Qualified",
      level: 1,
      permissions: ["view",, "add",],
      customPermissions: ["Edit Details", "On Hold"],
    },
    {
      name: "Applicants",
      level: 0,
      permissions: [],
      customPermissions: [],
    },
    {
      name: "Shortlisted",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
    {
      name: "Final Review",
      level: 1,
      permissions: ["view", "add"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
    {
      name: "Hold",
      level: 1,
      permissions: ["view", "add", "edit"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
    {
      name: "Not Qualified",
      level: 1,
      permissions: ["view", "add", "edit", "delete"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
    {
      name: "Employees",
      level: 0,
      permissions: [],
      customPermissions: [],
    },
    {
      name: "Incomplete Profile",
      level: 1,
      permissions: ["view", "edit"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
    {
      name: "Active Employee",
      level: 1,
      permissions: ["view", "add"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
    {
      name: "Inactive Employee",
      level: 1,
      permissions: ["view", "edit"],
      customPermissions: ["Add New", "Edit", "Hold", "Not Qualified", "Export"],
    },
  ]


export const CompanyPermissions = [
    {
      name: "Dashboard",
      level: 0,
      permissions: ["view"],
      customPermissions: ["Request", "Cards Overview"],
    },
    {
      name: "Employees",
      level: 0,
      permissions: ["view", "add", "edit", "delete"],
      customPermissions: ["Export", "Status", "Copy Link"],
    },
    {
      name: "Employee",
      level: 1,
      permissions: ["view", "add", "edit", "delete"],
      customPermissions: ["Add Employee","Export","Edit Details", "Status", "Copy Link"],
    },
    {
      name: "Advance Salary",
      level: 1,
      permissions: ["view", "add", "edit","delete"],
      customPermissions: ["Edit Details", "On Hold", "Delete Campaign"],
    },
    {
      name: "Driving License",
      level: 1,
      permissions: ["view", "add", "edit", "delete"],
      customPermissions: ["Edit Details", "On Hold", "Delete Campaign", "Status"],
    },
    {
      name: "Employee Clearance",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export"],
    },
    {
      name: "Employee Imformation",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details", "Status", "Copy Link"],
    },
    {
      name: "Employee Transfer Form",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export"],
    },
    {
      name: "Food Permit Deduction",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details", "Status"],
    },
    {
      name: "General Deduction",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details"],
    },
    {
      name: "Passport Acceptance",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details", "Status", "Copy Link"],
    },
    {
      name: "Payroll",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details", "Status", "Copy Link"],
    },
    {
      name: "Special Allowance",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details"],
    },
    {
      name: "Loan",
      level: 1,
      permissions: ["view"],
      customPermissions: ["Add Employee", "Export", "Edit Details"],
    },
    {
      name: "Asset Allocation",
      level: 0,
      permissions: ["view"],
      customPermissions: ["Request","Cards Overview"],
    },
    {
      name: "Asset Clearance",
      level: 0,
      permissions: ["view"],
      customPermissions: ["Request","Cards Overview"],
    },
  ]