export const rolesTemplateListData = [
  {
    id: 1,
    role: "Administrator",
    roleColor: "green",
    userType: "Company User",
    createdDate: "31-12-2023",
    status: true,
    action: "...",
  },
  {
    id: 2,
    role: "Support",
    roleColor: "orange",
    userType: "Global User",
    createdDate: "27-12-2023",
    status: false,
    action: "...",
  },
  {
    id: 3,
    role: "Restricted",
    roleColor: "red",
    userType: "Company User",
    createdDate: "16-12-2023",
    status: false,
    action: "...",
  },
  {
    id: 4,
    role: "Administrator",
    roleColor: "green",
    userType: "Global User",
    createdDate: "31-12-2023",
    status: true,
    action: "...",
  },
  {
    id: 5,
    role: "Support",
    roleColor: "orange",
    userType: "Company User",
    createdDate: "27-12-2023",
    status: true,
    action: "...",
  },
];
