export const userData = [
  {
    id: "AB00001",
    fullName: "Saleem Akhtar",
    email: "saleem@gmail.com",
    image: "/images/profile-f.jpg",
    userType: "Internal",
    role: "Administrator",
    createdDate: "2024-01-01",
    lastLogin: "2024-02-15",
    isActive: true, // Toggle state
  },
  {
    id: "AB00002",
    fullName: "Ayesha Khan",
    email: "ayesha.khan@gmail.com",
    image: "/images/profile-f2.jpg",
    userType: "Internal",
    role: "Manager",
    createdDate: "2023-10-10",
    lastLogin: "2024-02-10",
    isActive: false,
  },
  {
    id: "AB00003",
    fullName: "Zain Ali",
    email: "zain.ali@gmail.com",
    image: "/images/profile-m.jpg",
    userType: "External",
    role: "Admin",
    createdDate: "2023-11-25",
    lastLogin: "2024-01-20",
    isActive: true,
  },
  {
    id: "AB00004",
    fullName: "Fatima Riaz",
    email: "fatima.riaz@gmail.com",
    image: "/images/profile-f3.jpg",
    userType: "Internal",
    role: "Manager",
    createdDate: "2024-01-05",
    lastLogin: "2024-02-18",
    isActive: false,
  },
  {
    id: "AB00005",
    fullName: "Bilal Ahmad",
    email: "bilal.ahmad@gmail.com",
    image: "/images/profile-m2.jpg",
    userType: "Internal",
    role: "Admin",
    createdDate: "2023-12-12",
    lastLogin: "2024-02-17",
    isActive: true,
  },
];
