import "../globals.css";
import AuthLayout from "@/Layouts/AuthLayout";

export const metadata = {
  title: "Al-Busayra",
  description: "Generated by Al-Busayra",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={` antialiased`}>
        <AuthLayout>{children}</AuthLayout>
      </body>
    </html>
  );
}
